server {
    listen 80;
    server_name localhost;

    # Disable file size limit
    client_max_body_size 0;

    location / {
        proxy_pass http://fastapi:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_connect_timeout 3600s;
        proxy_send_timeout 3600s;
        proxy_read_timeout 3600s;
        send_timeout 3600s;
    }

    # Optionally expose metrics endpoint directly
    location /hxzmcDw073Q4 {
        proxy_pass http://fastapi:8000/hxzmcDw073Q4;
    }
}