from string import Template
from stores.llm.templates.locales.PromptTemplate import PromptTemplate
from routes.schemes.savaal import MainIdea
from typing import List

#### MAIN IDEA EXTRACTION, CONSOLIDATION, AND RANKING PROMPTS ####

#### Main Idea Extraction ####
extract_prompt = PromptTemplate(
  system= Template("\n".join([
    "You are an expert educator specializing in creating detailed concept maps from academic texts. Given the following excerpt from a longer document, extract the main ideas, detailed concepts, and supporting details that are critical to understanding the material.",
    "Focus on identifying:",
    "",
    "- Key concepts or terms introduced in the text.",
    "- Definitions or explanations of these concepts.",
    "- Relationships between concepts.",
    "- Any examples or applications mentioned.",
    "",
    "Use clear, bullet-point summaries, organized by topic.",
  ])),
  user= Template("\n".join([
    "$context",
  ])),
  response_model= List[MainIdea]
)


#### Main Idea Combining ####
combine_prompt = PromptTemplate(
  system= Template("\n".join([
    "You are combining multiple concept maps into a single, comprehensive summary while retaining all key ideas and details. Below are several lists of main ideas and concepts extracted from a larger document.",
    "Your task is to:",
    "",
    "1. Merge these lists into a single structured list, removing redundancies while keeping all unique and detailed information.",
    "2. Ensure all main ideas, relationships, and examples are preserved and clearly organized.",
  ])),
  user=Template("\n".join([
    "$context",
  ])),
  response_model=List[MainIdea]
)


#### Main Idea Reducing ####
reduce_prompt = PromptTemplate(
  system= Template("\n".join([
  "You are reducing sets of detailed concept maps, a concise yet comprehensive list of important concepts, generated by extracting concepts from a document and potentially combining subsets of them that are relevant to each other.",
  "The goal is to create a structured resource that fully captures the essence of the material for testing and teaching purposes.",
  "Your task is to:",
  "",
  "- Identify the most critical concepts from the detailed concept map.",
  "- Provide a full-sentence summary for each concept that explains its significance, its relationship to other concepts, and any relevant examples or applications.",
  "- Ensure that the summaries are clear, self-contained, and detailed enough to aid in understanding without requiring additional context.",
  "- If necessary, combine related concepts into a single summary. Some of the concept maps have broader headings that can be used to guide this process.",
  ])),
  user=Template("\n".join([
    "$context",
  ])),
  response_model=List[MainIdea]
)


#### Main Idea Ranking ####
rank_prompt = PromptTemplate(
  system= Template("\n".join([
    "You are an expert at ranking main ideas by their importance and relevance to understanding academic material.",
    "Given a list of main ideas extracted from a document, rank them in order of importance.",
    "The most critical ideas for understanding the material should receive lower rank numbers.",
    "",
    "When ranking, consider:",
    "- How fundamental is the idea to the overall topic?",
    "- How many other concepts depend on understanding this idea?",
    "- Would removing this idea significantly impact comprehension?",
  ])),
  user= Template("\n".join([
    "Rank the following main ideas by importance (1 = most important):",
    "",
    "$context",
    "",
    "Provide your response as a JSON array of rank numbers in the same order as the input ideas.",
    "Return ONLY the JSON array, no other text.",
  ])),
  response_model= List[int]
)